enum SCOLARITY_TYPE {
  ENSINO_FUNDAMENTAL_I = 'ENSINO_FUNDAMENTAL_I',
  ENSINO_FUNDAMENTAL_C = 'ENSINO_FUNDAMENTAL_C',
  ENSINO_MEDIO_I = 'ENSINO_MEDIO_I',
  ENSINO_MEDIO_C = 'ENSINO_MEDIO_C',
  TECNICO_I = 'TECNICO_I',
  TECNICO_C = 'TECNICO_C',
  ENSINO_SUPERIOR_I = 'ENSINO_SUPERIOR_I',
  ENSINO_SUPERIOR_C = 'ENSINO_SUPERIOR_C',
}

export default SCOLARITY_TYPE;
